//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CategoryBasedMetaTags
    {
        public int CategoryBasedMetaTagsID { get; set; }
        public string FocusAreaName { get; set; }
        public string SubFocusAreaName { get; set; }
        public string Title { get; set; }
        public string TwitterTitle { get; set; }
        public string Descriptions { get; set; }
        public Nullable<bool> IsService { get; set; }
    }
}
