//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyVote
    {
        public int CompanyVoteID { get; set; }
        public int CompanyID { get; set; }
        public int UserID { get; set; }
        public System.DateTime VotedDate { get; set; }
    
        public virtual Company Company { get; set; }
        public virtual User User { get; set; }
    }
}
