//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotationRateCard
    {
        public int QuotationRateCardID { get; set; }
        public string MainCategory { get; set; }
        public string SubCategory { get; set; }
        public string Ctypes { get; set; }
        public string Classname { get; set; }
        public Nullable<decimal> MinPriceZone1 { get; set; }
        public Nullable<decimal> MaxPriceZone1 { get; set; }
        public Nullable<decimal> MinPriceZone2 { get; set; }
        public Nullable<decimal> MaxPriceZone2 { get; set; }
        public Nullable<decimal> MinPriceZone3 { get; set; }
        public Nullable<decimal> MaxPriceZone3 { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
    }
}
