//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Softwares
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Softwares()
        {
            this.SoftwareCategory = new HashSet<SoftwareCategory>();
        }
    
        public int SoftwareID { get; set; }
        public string SoftwareName { get; set; }
        public string LogoName { get; set; }
        public string TagLine { get; set; }
        public string PriceRange { get; set; }
        public string SoftwareTrail { get; set; }
        public string DemoURL { get; set; }
        public string DomainID { get; set; }
        public string WebSiteURL { get; set; }
        public string LinkedInURL { get; set; }
        public string FaceBookURL { get; set; }
        public string TwitterURL { get; set; }
        public string InstagramURL { get; set; }
        public Nullable<int> FoundedYear { get; set; }
        public string SoftwareDescription { get; set; }
        public int CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsUserApproved { get; set; }
        public Nullable<System.DateTime> UserApprovedDate { get; set; }
        public Nullable<bool> IsAdminApproved { get; set; }
        public Nullable<System.DateTime> AdminApprovedDate { get; set; }
        public string WorkEmail { get; set; }
        public string Remarks { get; set; }
        public string SoftwareOTP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SoftwareCategory> SoftwareCategory { get; set; }
        public virtual User Users { get; set; }
    }
}
