//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubFocusArea
    {
        public int SubFocusAreaID { get; set; }
        public Nullable<int> FocusAreaID { get; set; }
        public string SubFocusAreaName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual FocusArea FocusArea { get; set; }
    }
}
