//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamMembers
    {
        public int MemberID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> SoftwareID { get; set; }
        public string MemberName { get; set; }
        public string PictureName { get; set; }
        public string EmailID { get; set; }
        public string Designation { get; set; }
        public string LinkedInProfile { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    }
}
