//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpVotes.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserQuotation
    {
        public int UserQuotationID { get; set; }
        public string PlatformType { get; set; }
        public string ThemeType { get; set; }
        public string LoginsecurityType { get; set; }
        public string ProfileType { get; set; }
        public string SecurityType { get; set; }
        public string ReviewrateType { get; set; }
        public string ServiceType { get; set; }
        public string DatabaseType { get; set; }
        public string FeaturesType { get; set; }
        public string EmailID { get; set; }
        public string Name { get; set; }
        public string CompanyName { get; set; }
    }
}
